stages:
  download:
    cmd: Rscript stages/1_download.R
    deps:
      - stages/1_download.R
    outs:
      - download/
  process:
    cmd: Rscript stages/2_process.R
    deps:
      - download/
      - stages/2_process.R
    outs:
      - brick/
  rml:
    cmd: bash stages/3_rml.sh
    deps:
      - brick/
      - stages/3_rml.sh
      - deps.edn
      - stages/rml.clj
    outs:
      - rdf/
