stages:
  download:
    cmd: Rscript R/download.R
    deps:
      - R/download.R
    outs:
      - download/
  process:
    cmd: Rscript R/process.R
    deps:
      - download/
      - R/process.R
    outs:
      - data/
  rml:
    cmd: bash rml.sh
    deps:
      - data/
      - rml.sh
      - hgnc_complete_set.rml.ttl
      - morph-kgc.ini
    outs:
      - rdf/
