stages:
  download:
    cmd: Rscript R/download.R
    deps:
      - R/download.R
    outs:
      - download/:
          cache: false
  process:
    cmd: Rscript R/process.R
    deps:
      - download/
      - R/process.R
    outs:
      - data/
      
